= Общие сведения о модуле

_{mir}_ является дополнительным модулем {dv}, который добавляет поддержку работы с цифровой платформой распределённого реестра ФНС ({cr}) через сервис {kd}.

Модуль представляет собой серверное расширение для модуля Службы {ws} и позволяет выполнять регистрацию, отзыв и проверку МЧД в {cr} через сервис {kd}.

Модуль поддерживает работу через {wc}.

С помощью модуля {mc} можно настраивать подключение к сервису {kd} и отслеживать проблемы, возникающие при взаимодействии с сервисом, просматривать возникшие ошибки и повторять обработку сообщений в случае необходимости.

[#purpose-function]
== Назначение и функции модуля

.Модуль предоставляет следующие возможности:
. Отправка МЧД на регистрацию в {cr}.
. Отзыв МЧД, зарегистрированной в {cr}.
. Проверка действительности МЧД в {cr} и отображение результата проверки в _Журнале обмена с реестром МЧД_.

[#doc-list]
== Разделы документации

.Документация модуля содержит следующие разделы:
. Общие сведения о модуле.
. Администрирование модуля.
. Руководство разработчика модуля.
