= {log}

Карточка содержит в себе таблицу, которая строится на основании карточки журнала обмена сообщениями соответствущей СКД.

// * Тип события: "Из {dv}" или "От сервиса для управления МЧД".
// * Дата и время.
// * Описание события:
// +
// ** Заявка на регистрацию отправлена в сервис для управления МЧД
// ** Заявка на регистрацию МЧД выполнена
// ** Заявка на регистрацию МЧД не выполнена
// ** В процессе выполнения операции возникли проблемы
// +
// * Статус события:
// +
// ** Запрос отправлен
// ** Ошибка обработки
// ** Обработка прошла успешно

.Таблица имеет следующие колонки:
* _Дата/время_ -- в колонке указывается дата и время получения ответа от {kd}. В случае возникновения ошибки в колонке указывается дата выполнения запроса к {kd}.
* _Событие_ -- тип события, производимого с МЧД: Регистрация МЧД в реестре ФНС, Отзыв МЧД или Проверка статуса МЧД в реестре.
* _Результат_ -- в колонке отображается описание события, производимого с МЧД: запрос в обработке, МЧД успешно зарегистрирована/отозвана. Также в колонке указывается текущий статус МЧД: действует, отозвана, просрочена, не наступил срок начала действия. +
Если при обработке запроса произошла ошибка, отображается соответствующее сообщение.
