= Структура модуля

{mir} содержит в себе бизнес-логику: операции регистрации, отзыва и проверки статуса.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Расширение для Службы {ws} -- _{mir}_.
.. Серверное расширение {wc}а, сигнализирующее модулю о необходимости зарегистрировать МЧД.
// .. Журнал обмена с реестром МЧД -- карточка, которая соответствует каждой СКД. После установки {of-mir} добавляется следующая логика: при обращении к модулю из какой-либо карточки доверенности, в СКД появляется ссылка на журнал и в журнале сразу появляется запись. Например, о нажатии кнопки *Зарегистрировать МЧД* -- создается карточка журнала и в ней запись о том, что МЧД была отправлена на регистрацию.
.. Библиотеки API модуля.

[#inner-links]
== Сведения о связях между составными частями модуля

Модуль отслеживает сообщение о необходимости регистрации, проверки или отзыва МЧД в карточке сообщений. При получении запроса, сервис формирует соответствующее обращение в {kd}. После выполнения запроса в _{log}_ добавляется запись о запросе, и поля карточки xref:system:ROOT:terms.adoc#attorney[СКД] изменяются соответствующим образом.

Действия с доверенностью отслеживаются и могут быть просмотрены через сообщения {of-mc}.

[#outer-links]
== Сведения о связях с другими системами

_{mir}_ является промежуточным звеном в связи системы {dv} с оператором {kd}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций взаимодействия с {cr} через {kd}.
