= Структура модуля

{mir} содержит в себе бизнес-логику: операции отправки МЧД на регистрацию, отзыва и проверки состояния.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Расширение для Службы {ws} -- _{mir}_.
.. Серверное расширение {wc}а, сигнализирующее модулю о необходимости зарегистрировать МЧД.
.. Журнал обмена с реестром МЧД -- карточка, которая соответствует каждой СКД. После установки {of-mir} добавляется следующая логика: при обращении к модулю из какой-либо карточки доверенности, в СКД появляется ссылка на журнал и в журнале сразу появляется запись. Например, о нажатии кнопки *Зарегистрировать МЧД* -- создается карточка журнала и в ней запись о том, что МЧД была отправлена на регистрацию.
.. Библиотеки API модуля.

[#inner-links]
== Сведения о связях между составными частями модуля

Модуль отслеживает сообщение о необходимости регистрации или отзыва МЧД в карточке сообщений. При получении запроса, сервис формирует обращение, содержащее запрос на регистрацию или отзыв, в {kd}. Модуль выполняет запросы в {kd} для проверки факта регистрации или отозванности доверенности. После подтверждения факта, в _{log}_ добавляется соответствующая запись, поля карточки xref:system:ROOT:terms.adoc#attorney[СКД] изменяются соответствующим образом.

[#outer-links]
== Сведения о связях с другими системами

_{mir}_ является промежуточным звеном в связи системы {dv} с оператором {kd}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций интеграции с централизованным государственным реестром МЧД через {kd}.
