= Структура модуля

{mir} содержит в себе бизнес-логику: операции отправки МЧД на регистрацию, отзыва и проверки состояния.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Серверное расширение модуля {bo} -- _{mir}_.
.. Специальное расширение {wc}а, сигнализирующее модулю о необходимости зарегистрировать МЧД.
.. Карточка сообщений {of-mir} -- общая карточка для всех МЧД. В эту карточку записываются сообщения для Службы {ws}, о том, что с определенной МЧД необходимо выполнить операцию регистрации или отзыва. Из таких сообщений будет формироваться очередь к процессу Службы {ws}.

[#inner-links]
== Сведения о связях между составными частями модуля

Модуль отслеживает сообщение о необходимости регистрации или отзыва МЧД в карточке сообщений. При получении запроса, сервис формирует обращение, содержащее запрос на регистрацию или отзыв, в {kd}. Модуль получает подтверждение регистрации обращения и выполняет запросы с заданной периодичностью отправляет запросы в {kd} для проверки факта регистрации или отозванности доверенности. После подтверждения факта, в _{log}_ добавляется соответствующая запись, поля карточки xref:system:ROOT:terms.adoc#attorney[СКД] изменяются соответствующим образом.

[#outer-links]
== Сведения о связях с другими системами

_{mir}_ является промежуточным звеном в связи системы {dv} с оператором {kd}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций интеграции с централизованным государственным реестром МЧД через {kd}.
