= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению не предъявляются.

[#software]
== Необходимое программное обеспечение

* СКЗИ КриптоПро CSP версии {csp-v} должно быть установлено на клиентских машинах и сервере/серверах СУБП (Workflow). См. подробнее требования в документации модуля xref:dev@backoffice::requirements.adoc#crypto-pro[{bo}].
// * Для подписания документов через {wc} необходимо установить xref:5.5.5@backoffice:admin:prepare-cryptopro.adoc[компоненты] КриптоПро TSPCOM и OSPCOM на клиентских компьютерах.

[#network]
== Требования к каналам связи

Администратор локальной сети должен обеспечить возможность подключения с сервера {dv} и серверов СУБП к сервису {kd}.

// tag::url[]
* Стандартная точка подключения: \https://m4d-api.kontur.ru.
* Адрес тестового сервера Диадок: \https://m4d-api-staging.testkontur.ru
// end::url[]

[#docsvision]
== Требования к системе {dv}

Модули {dv}::
// . Серверная и клиентская части модуля _{pl}_ версии {pl-req} и выше.
. Серверная и клиентская части модуля _{bo}_ с поддержкой СКД версии {bo-req} и выше.
. Серверная и клиентская части модуля _Служба {ws}_ версии {ws-req} и выше для работы через web-интерфейс.
. Серверная часть модуля _{mc}_ версии {mc-req} и выше.
. Серверная и клиентская части модуля {wc} 17 (любой сборки) для работы через web-интерфейс с использованием примера решения МЧД из https://github.com/Docsvision/m4d-sample.git[репозитория {dv} на GitHub].

[#license]
== Лицензия

.Для работы с модулем {mir}:
* Лицензия на систему {dv} должна содержать дополнительную опцию _Docsvision 5 Модуль регистрации МЧД_.
* В зависимости от используемой подписиfootnote:[См. раздел "xref:5.5.5@backoffice:admin:system-settings.adoc#signature-cypher[Подписи и шифрование]" в документации по администрированию модуля {bo}.] на стороне клиента может потребоваться лицензия на компоненты КриптоПро TSPCOM и OSPCOM.

// NOTE: Обращение к xref:programmer:api/IEdiPowerOfAttorneyService.adoc[сервису для работы с МЧД] и его методов, их поддержка в `EdiScriptHelper` может использоваться для реализации в {wincl}е. В  _Коннекторе к Диадок_ работа с МЧД реализована на стороне Диадок.

[#other]
== Прочие требования

Учётная запись в системе {kd}. Для регистрации, отзыва и проверки МЧД в {cr} через сервис {kd} необходимо быть зарегистрированным пользователем данной системы. Регистрация организации в системе "{kd}" выполняется самостоятельно.

Для отправки МЧД в {cr}, отзыва и проверки контрагентов требуется подключение к "{kd}" с тарифом, включающим оплату доступа к API. В противном случае при операциях с МЧД в журнале сервера будет появляться ошибка "Необходима оплата тарифа АПИ". Если учетная запись используется в нескольких независимых организациях с разными тарифами, конкретно для модуля интеграции с реестром МЧД можно сделать отдельную учетную запись и добавить её только в организации с доступом к API.

[NOTE]
====
Информация о подключении к оператору "{kd}" приведена на сайте https://www.diadoc.ru/.
====
