= Проверка статуса МЧД в {cr}

.Чтобы проверить в {cr} статус регистрации МЧД, полученной от контрагента:
. Выполните необходимые настройки подключения к {cr} как описано в разделе xref:admin:connection-settings.adoc[].
. Нажмите на добавленную в документ кнопку *Проверить МЧД*, чтобы передать на проверку номер доверенности, полученной от контрагента.
+
В {cr} будет отправлена текущая дата или дата подписания МЧД. В результате проверки в пользовательском интерфейсе будет отображён актуальный статус доверенности контрагента на указанную дату.
+
Также проверяется факт отзыва доверенности. Если доверенность была отозвана или процесс отзыва ещё не завершён, сообщение об этом будет выведено на экране.
+
. В случае успешного отзыва на экран будет выведено сообщение об этом. Соответствующая информация также будет записана в _Журнал обмена с реестром МЧД_.

NOTE: При проверке передоверия может возникать ошибка `Проверка передоверия была запрошена некорректно`, так как сервис {kd} пока не настроил работу с передоверием.
