= Регистрация МЧД в реестре

// Сообщения о необходимых операциях с МЧД, например, операции регистрации, записываются в _Карточку сообщений {of-mir}_.

.Чтобы отправить МЧД на регистрацию в реестр:
. Выполните необходимые настройки подключения к реестру как описано в разделе xref:admin:connection-settings.adoc[].
. Нажмите на добавленную в документ кнопку *Зарегистрировать МЧД*, чтобы передать код доверенности, ИНН организации для регистрации МЧД в {cr}.
+
* При отправке МЧД на регистрацию выполняется проверка наличия xref:system:ROOT:terms.adoc#attorney[СКД], электронной подписи, файла `.xml` и регистрационного номера доверенности. В случае отсутствия чего-либо на экран будет выведено информационное сообщение.
* Доверенность будет отправлена на регистрацию в реестр, после чего в карточку доверенности и {log} будет записан статус регистрации: МЧД передана на регистрацию или МЧД успешно зарегистрирована. Если в процессе регистрации возникает ошибка, она будет записана в {log}.
+
. На экран будет выведено уведомление об успешной или неуспешной регистрации. Информация о регистрации также будет записана в Журнал обмена с реестром МЧД.
