= Настройка подключения к централизованному реестру МЧД

Модуль отслеживает сообщение о необходимости регистрации МЧД в карточке сообщений. При получении запроса формирует обращение, содержащее запрос на регистрацию, в {kd}. Модуль получает подтверждение регистрации обращения и выполняет запросы с заданной периодичностью отправляет запросы в {kd} для проверки факта регистрации доверенности. После подтверждения факта регистрации доверенности в _{log}_ добавляется соответствующая запись, поля карточки СКД изменяются соответствующим образом.

Все действия с доверенностью отслеживаются и могут быть просмотрены через сообщения {of-mc}.

Администратор должен настроить расширение для модуля {bo} в модуле {mc}.

[#register]
== Регистрация МЧД

.Чтобы иметь возможность регистрировать МЧД в распределённом реестре, выполните следующие действия:
. Создайте вид карточки для работы с МЧД. Для {wc}а можно воспользоваться готовым примером. Для этого нужно импортировать вид карточки документа ПКД menu:PowersOfAttorney[Data > SolutionOfPOA.sol] из примера "xref:5.5.17@webclient:programmer:other/powers-of-attorney.adoc[]".
. В разметку просмотра МЧД (версия 002) добавьте ЭУ `_Кнопка_`, например, *Зарегистрировать МЧД*, и добавьте скрипт `sendForRegistrationToRegistry` для события `*При щелчке*`.

[#recall]
== Отзыв МЧД

.Чтобы иметь возможность отозвать МЧД, зарегистрированную в распределённом реестре, выполните следующие действия:
. Создайте вид карточки для работы с МЧД. Для {wc}а можно воспользоваться готовым примером. Для этого нужно импортировать вид карточки документа ПКД menu:PowersOfAttorney[Data > SolutionOfPOA.sol] из примера "xref:5.5.17@webclient:programmer:other/powers-of-attorney.adoc[]".
. В разметку просмотра МЧД (версия 002) добавьте ЭУ `_Кнопка_`, например, *Отозвать МЧД*, и добавьте скрипт `recallPowerOfAttorney` для события `*При щелчке*`.

[#check]
== Проверка МЧД

.Чтобы иметь возможность проверять в распределённом реестре статус МЧД, полученной от контрагента:
. Создайте вид карточки для работы с МЧД. Для {wc}а можно воспользоваться готовым примером. Для этого нужно импортировать вид карточки документа ПКД menu:PowersOfAttorney[Data > SolutionOfPOA.sol] из примера "xref:5.5.17@webclient:programmer:other/powers-of-attorney.adoc[]".
. В разметку просмотра МЧД (версия 002) добавьте ЭУ `_Кнопка_`, например, *Проверить МЧД*, и добавьте скрипт `checkPowerOfAttorney` для события `*При щелчке*`.
